/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DeepcrawlAppError } from "./deepcrawlapperror.js";

export type BaseErrorResponseData = {
  success: boolean;
  /**
   * The URL that was being processed when the error occurred
   */
  targetUrl: string;
  /**
   * Error message describing what went wrong
   */
  error: string;
};

export class BaseErrorResponse extends DeepcrawlAppError {
  success: boolean;
  /**
   * The URL that was being processed when the error occurred
   */
  targetUrl: string;
  /**
   * Error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: BaseErrorResponseData;

  constructor(
    err: BaseErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.targetUrl = err.targetUrl;
    this.error = err.error;

    this.name = "BaseErrorResponse";
  }
}

/** @internal */
export const BaseErrorResponse$inboundSchema: z.ZodType<
  BaseErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  targetUrl: z.string(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new BaseErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BaseErrorResponse$Outbound = {
  success: boolean;
  targetUrl: string;
  error: string;
};

/** @internal */
export const BaseErrorResponse$outboundSchema: z.ZodType<
  BaseErrorResponse$Outbound,
  z.ZodTypeDef,
  BaseErrorResponse
> = z.instanceof(BaseErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    targetUrl: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BaseErrorResponse$ {
  /** @deprecated use `BaseErrorResponse$inboundSchema` instead. */
  export const inboundSchema = BaseErrorResponse$inboundSchema;
  /** @deprecated use `BaseErrorResponse$outboundSchema` instead. */
  export const outboundSchema = BaseErrorResponse$outboundSchema;
  /** @deprecated use `BaseErrorResponse$Outbound` instead. */
  export type Outbound = BaseErrorResponse$Outbound;
}
