/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { readUrl } from "../../funcs/readUrl.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ReadUrlRequest$inboundSchema,
};

export const tool$readUrl: ToolDefinition<typeof args> = {
  name: "read-url",
  description: `Returning full result object from the request URL.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await readUrl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
