/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DeepcrawlAppError } from "./deepcrawlapperror.js";
import {
  LinksTree,
  LinksTree$inboundSchema,
  LinksTree$Outbound,
  LinksTree$outboundSchema,
} from "./linkstree.js";

export type ErrorsLinksPostErrorResponseData = {
  success: boolean;
  /**
   * The URL that was being processed when the error occurred
   */
  targetUrl: string;
  /**
   * Error message describing what went wrong
   */
  error: string;
  /**
   * ISO timestamp when the error occurred
   */
  timestamp: string;
  tree?: LinksTree | null | undefined;
};

export class ErrorsLinksPostErrorResponse extends DeepcrawlAppError {
  success: boolean;
  /**
   * The URL that was being processed when the error occurred
   */
  targetUrl: string;
  /**
   * Error message describing what went wrong
   */
  error: string;
  /**
   * ISO timestamp when the error occurred
   */
  timestamp: string;
  tree?: LinksTree | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorsLinksPostErrorResponseData;

  constructor(
    err: ErrorsLinksPostErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.targetUrl = err.targetUrl;
    this.error = err.error;
    this.timestamp = err.timestamp;
    if (err.tree != null) this.tree = err.tree;

    this.name = "ErrorsLinksPostErrorResponse";
  }
}

/** @internal */
export const ErrorsLinksPostErrorResponse$inboundSchema: z.ZodType<
  ErrorsLinksPostErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  targetUrl: z.string(),
  error: z.string(),
  timestamp: z.string(),
  tree: z.nullable(LinksTree$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorsLinksPostErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorsLinksPostErrorResponse$Outbound = {
  success: boolean;
  targetUrl: string;
  error: string;
  timestamp: string;
  tree?: LinksTree$Outbound | null | undefined;
};

/** @internal */
export const ErrorsLinksPostErrorResponse$outboundSchema: z.ZodType<
  ErrorsLinksPostErrorResponse$Outbound,
  z.ZodTypeDef,
  ErrorsLinksPostErrorResponse
> = z.instanceof(ErrorsLinksPostErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    targetUrl: z.string(),
    error: z.string(),
    timestamp: z.string(),
    tree: z.nullable(LinksTree$outboundSchema).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorsLinksPostErrorResponse$ {
  /** @deprecated use `ErrorsLinksPostErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ErrorsLinksPostErrorResponse$inboundSchema;
  /** @deprecated use `ErrorsLinksPostErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ErrorsLinksPostErrorResponse$outboundSchema;
  /** @deprecated use `ErrorsLinksPostErrorResponse$Outbound` instead. */
  export type Outbound = ErrorsLinksPostErrorResponse$Outbound;
}
