/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * How to order links within each folder: "page" (preserve original order) or "alphabetical" (sort A→Z by URL).
 */
export const LinksOrder = {
  Page: "page",
  Alphabetical: "alphabetical",
} as const;
/**
 * How to order links within each folder: "page" (preserve original order) or "alphabetical" (sort A→Z by URL).
 */
export type LinksOrder = ClosedEnum<typeof LinksOrder>;

/** @internal */
export const LinksOrder$inboundSchema: z.ZodNativeEnum<typeof LinksOrder> = z
  .nativeEnum(LinksOrder);

/** @internal */
export const LinksOrder$outboundSchema: z.ZodNativeEnum<typeof LinksOrder> =
  LinksOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinksOrder$ {
  /** @deprecated use `LinksOrder$inboundSchema` instead. */
  export const inboundSchema = LinksOrder$inboundSchema;
  /** @deprecated use `LinksOrder$outboundSchema` instead. */
  export const outboundSchema = LinksOrder$outboundSchema;
}
